data:
  organised_data_folder_path: "data/data_sources"
  shakespeare_data_source: "dataset_shakespeare_collection.json"
  impostors_data_source: "dataset_impostors.json"
  all_impostors_data_source: "dataset_all_impostors.json"
  classify_text_data_source: "text_to_classify.json"
  shakespeare_path: "data/raw/shakespeare"
  impostors_path: "data/raw/impostors"
  fine_tuned_bert_model_path: "saved_trained_models/berts/"
  trained_branches_path: "saved_trained_models/models/"
  pairs: "pairs.json"

training:
  optimizer:
    initial_learning_rate: 1e-3
    learning_rate_decay_factor: 0.1
    gradient_clipping_threshold: 1.0 # or 5.0
  training_batch_size: 8
  epochs: 10
  early_stopping_patience: 2
  impostor_chunk_ratio: 4
  test_split: 0.25

model:
  chunk_to_batch_ratio: 8
  chunk_size: 50
  cnn:
    filters: 500 # 128 or 256
    padding: "valid"
    kernel_size: [3, 6, 12]
    pool_size: 1
  bilstm:
    dropout: 0.25 # 0.2 - 0.5
    units: 1000
  fc:
    in_features: 512
    out_features: 512

isolation_forest:
  number_of_trees: 100

bert:
  model: "bert-base-uncased"
  repository: "ElyMK1/bert-shakespeare-english-mlm"
  max_sequence_length: 512
  mlm_probability: 0.15
  train_batch_size: 16
  num_epochs: 5
  save_steps: 1000
  save_total_limit: 2
  logging_steps: 500
  logging_dir: "logs/shakespeare"
  token: "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"


wandb:
  enabled: True
  run_name: "full-procedure-run"
  project: "siamese-authorship-verification"
  artifact_name: "siamese-authorship-verification-branches"
  api_key: 99cb11ef59cac847e6b99323c0d485a69157f548