data:
  processed_tested_path: "data/processed/dataset_tested_collection.json"
  processed_impostors_path: "data/processed/dataset_impostors.json"
  trained_models_path: "saved_trained_models/"
  shakespeare_path: "data/raw/shakespeare"
  impostors_path: "data/raw/impostors"

training:
  optimizer:
    initial_learning_rate: 1e-4
    gradient_clipping_threshold: 1.0 # or 5.0
  batch_size: 400 # 32 # or 64 - How many chunks in a batch
  chunk_factor: 8 # Chunk to Batch ratio
  epochs: 5 # 10-20
  early_stopping_patience: 2
  impostor_chunk_ratio: 2
  validation_split: 0.25

model:
  save_trained_models: True
  load_trained_models: True
  cnn:
    filters: 128 # 128 or 256
    padding: "valid"
    kernel_size: [3, 6, 12]
    pool_size: 1
  bilstm:
    dropout: 0.25 # 0.2 - 0.5
    number_of_layers: 500
  fc:
    in_features: 128
    out_features: 1

isolation_forest:
  number_of_trees: 100

bert:
  model: "bert-base-uncased"
  maximum_sequence_length: 512
  trainable: True

wandb:
  enabled: True
  run_name: "full-procedure-run"
  project: "siamese-authorship-verification"
  api_key: 99cb11ef59cac847e6b99323c0d485a69157f548