data:
  processed_tested_path: "data/processed/dataset_tested_collection.json"
  processed_impostors_path: "data/processed/dataset_impostors.json"
  trained_models_path: "saved_trained_models/"
  shakespeare_path: "data/raw/shakespeare"
  impostors_path: "data/raw/impostors"

training:
  optimizer:
    initial_learning_rate: 1e-4
    learning_rate_decay_factor: 0.1
    gradient_clipping_threshold: 1.0 # or 5.0
  batch_size: 200 # 32 # or 64 - How many chunks in a batch
  chunk_factor: 4 # Chunk to Batch ratio
  epochs: 1 # 10-20
  early_stopping_patience: 5
  impostor_chunk_ratio: 2

model:
  save_trained_models: True
  load_trained_models: True
  softmax_dim: 1 # Unused currently
  cnn:
    filters: 128 # 256
    stride: 1
    padding: "valid"
    kernel_size: [3, 6, 12]
  bilstm:
    hidden_units: 128 # 128 or 256
    dropout: 0.25 # 0.2 - 0.5
    number_of_layers: 100
  fc:
    in_features: 128
    out_features: 1

isolation_forest:
  number_of_trees: 100

bert:
  model: "bert-base-uncased"
  maximum_sequence_length: 64
  trainable: True

wandb:
  enabled: true
  run_name: "full-procedure-run"
  project: "siamese-authorship-verification"
  api_key: 99cb11ef59cac847e6b99323c0d485a69157f548